version: "3.0"
services:
  mongodb:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "mongodb"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      MONGO_URI: "mongodb://localhost:27017/"
      DATABASE_NAME: "weeve-module"
      COLLECTION_NAME: "temperature-data"
    ports:
      - 80:80
